# States
SELECTING_ACTION, SELECTING_TRANSACTION_DETAIL, ENTERING_INFO, NEW_TRANSACTION_END, SELECTING_TRANSACTION, SELECTING_CATEGORY, CATEGORIZE_TRANSACTIONS_END = range(7)

# SELECTING_ACTION callback data
ADD_NEW_TRANSACTION, CATEGORIZE_TRANSACTIONS = range(7, 9)

# ADD_NEW_TRANSACTION callback data
NEW_NAME, NEW_VALUE, NEW_CATEGORY, NEW_DONE = range(9, 13)

# NEW_DONE callback data
NEW_DONE_YES, NEW_DONE_NO = range(13, 15)

